openapi: 3.0.3
info:
  title: Pet Owner API
  version: 1.0.0
paths:
  /owners/{ownerId}/pets:
    get:
      summary: Получить список питомцев владельца с заданным ID
      parameters:
        - in: path
          name: ownerId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
  /pets:
    get:
      summary: Получить список всех питомцев
      parameters:
        - in: query
          name: ownerId
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        ownerId:
          type: integer
          format: int64